### ISSUE TITLE
Address Service Dictionary Threading issues

### ISSUE THREAD

**Issue by ferguswatkins** [WhoopInc/whoopdi-releases#2]
We should also address the thread safety issues around the `localServiceDict` in `WhoopDI`.

The `localServiceDict` is not thread safe and can be mutated across multiple threads leading to crashes when it is deallocated. 

This happens when one thread does a local injection and another thread is doing a separate injection at the same time.

**Comment by ncipollo** [comment]
Moved here: https://github.com/WhoopInc/WhoopDI/issues/13
